### ISSUE TITLE
i cannot install in FreePBX 13

### ISSUE THREAD

**Issue by mureithimaina** [Cynjut/SCCP_Manager#3]
when i try to install i get this,..[image](https://goo.gl/photos/R5ifXBCQzuUgmXPY9)

what is the sollution

**Comment by Cynjut** [comment]
Don't. It doesn't work on anything newer tha Asterisk 1.8 and FreePBX 11.
--
Sent from myMail for Android Tuesday, 31 January 2017, 10:58AM -06:00 from razorMureithi  notifications@github.com :

**Comment by mureithimaina** [comment]
thanks

**Comment by mafairnet** [comment]
@razorMureithi Have you done something to integrate your sccp phones to FReePBX? I'm seriously considering to create a new module or a new integration for SCCP/FreePBX13.

**Comment by Cynjut** [comment]
NO - I updated the program so that it will work with FreePBX versions 
before 11, but with the new BMO database interface, the old code just 
isn't considered safe anymore.

There are also several new interface template modules that the old code 
doesn't look like, and none of my customers are interested in bringing 
it up to date. If you want to make it work with the new FreePBX and 
Asterisk 13 semantics, knock yourself out.

Dave
